export enum TipoCronogramaEnum {
  ADMINISTRATIVO = 'ADMINISTRATIVO',
  SERVICIOS = 'SERVICIOS',
  RESIDENCIALES = 'RESIDENCIALES',
  CORPORATIVOS = 'CORPORATIVOS',
  PLANIFICACIONES = 'PLANIFICACIONES',
  OTROS = 'OTROS',
}

export enum TipoDocumentoEnum {
  CERTIFICACIONES = 'CERTIFICACIONES',
  FACTURAS = 'FACTURAS',
  REGLAMENTOS = 'REGLAMENTOS',
  ACTAS = 'ACTAS',
  DOCUMENTOS_TECNICOS = 'DOCUMENTOS_TECNICOS',
  OTROS = 'OTROS',
}
